import { useState } from 'react'
import { Link } from 'react-router-dom'
import {
  Sparkles,
  Save,
  ListPlus,
  Eraser,
  FileText,
  Code,
  Database,
  CheckSquare,
  AlertTriangle,
  ArrowRightCircle,
} from 'lucide-react'
import { useAppData } from '../context/AppDataContext'
import SuccessMessage from '../components/Common/SuccessMessage'
import LoadingSpinner from '../components/Common/LoadingSpinner'
import EmptyState from '../components/Common/EmptyState'

const AI_TASK_TYPES = [
  'Generate Project Plan',
  'Break Requirement into Tasks',
  'Recommend Next Task',
  'Identify Project Blockers',
  'Explain Implementation',
  'Generate Testing Checklist',
]

export default function AIMentorPage() {
  const { projects, generateAIResponse, addAIHistory, addTask } = useAppData()

  const [form, setForm] = useState({
    projectId: '',
    requirement: '',
    taskType: AI_TASK_TYPES[0],
  })
  const [errors, setErrors] = useState({})
  const [loading, setLoading] = useState(false)
  const [response, setResponse] = useState(null)
  const [savedEntry, setSavedEntry] = useState(null)
  const [success, setSuccess] = useState('')

  const validate = () => {
    const next = {}
    if (!form.projectId) next.projectId = 'Please select a project.'
    if (!form.requirement.trim()) next.requirement = 'Please enter a requirement or question.'
    setErrors(next)
    return Object.keys(next).length === 0
  }

  // Simulates calling the future POST /api/ai/plan endpoint.
  const handleGenerate = (e) => {
    e.preventDefault()
    if (!validate()) return
    setLoading(true)
    setResponse(null)
    setSavedEntry(null)
    // Simulate network delay for a realistic loading state.
    setTimeout(() => {
      const project = projects.find((p) => p.id === Number(form.projectId))
      const result = generateAIResponse(project.name, form.requirement, form.taskType)
      setResponse(result)
      setLoading(false)
    }, 1200)
  }

  const handleSave = () => {
    const project = projects.find((p) => p.id === Number(form.projectId))
    const entry = addAIHistory({
      projectId: project.id,
      taskType: form.taskType,
      userPrompt: form.requirement,
      aiResponse: JSON.stringify(response),
      modelName: 'gpt-oss:20b',
    })
    setSavedEntry(entry)
    setSuccess('Recommendation saved to AI History.')
  }

  const handleCreateTasks = () => {
    if (!response) return
    const allTasks = [
      ...response.frontendTasks,
      ...response.backendTasks,
      ...response.databaseTasks,
    ]
    allTasks.forEach((title) => {
      addTask({
        projectId: Number(form.projectId),
        title,
        description: `Generated by AI Mentor (${form.taskType}).`,
        priority: 'Medium',
        status: 'Pending',
        aiGenerated: true,
      })
    })
    setSuccess(`${allTasks.length} tasks created from the AI recommendation.`)
  }

  const handleClear = () => {
    setResponse(null)
    setSavedEntry(null)
    setForm({ projectId: '', requirement: '', taskType: AI_TASK_TYPES[0] })
    setErrors({})
  }

  const update = (field) => (e) => {
    setForm((prev) => ({ ...prev, [field]: e.target.value }))
  }

  return (
    <div>
      <div className="page-head">
        <div className="page-head-left">
          <h1>AI Mentor</h1>
          <p>Ask the AI mentor to break your requirements into development tasks.</p>
        </div>
      </div>

      <SuccessMessage message={success} onDismiss={() => setSuccess('')} />

      <div className="grid-2">
        {/* Request form */}
        <div className="card">
          <div className="card-header">
            <h2 className="card-title">
              <span className="flex items-center gap-1">
                <Sparkles size={18} style={{ color: 'var(--indigo-600)' }} />
                Ask AI Mentor
              </span>
            </h2>
          </div>
          <div className="card-body">
            <form onSubmit={handleGenerate} noValidate>
              <div className="form-group">
                <label className="form-label" htmlFor="ai-project">Select Project</label>
                <select
                  id="ai-project"
                  className={`form-control ${errors.projectId ? 'invalid' : ''}`}
                  value={form.projectId}
                  onChange={update('projectId')}
                >
                  <option value="">Choose a project...</option>
                  {projects.map((p) => (
                    <option key={p.id} value={p.id}>{p.name}</option>
                  ))}
                </select>
                {errors.projectId && <span className="form-error">{errors.projectId}</span>}
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="ai-requirement">Requirement or Question</label>
                <textarea
                  id="ai-requirement"
                  className={`form-control ${errors.requirement ? 'invalid' : ''}`}
                  value={form.requirement}
                  onChange={update('requirement')}
                  placeholder="e.g. I want users to apply to companies and track their applications."
                  rows={4}
                />
                {errors.requirement && <span className="form-error">{errors.requirement}</span>}
              </div>

              <div className="form-group">
                <label className="form-label" htmlFor="ai-task-type">AI Task Type</label>
                <select
                  id="ai-task-type"
                  className="form-control"
                  value={form.taskType}
                  onChange={update('taskType')}
                >
                  {AI_TASK_TYPES.map((t) => (
                    <option key={t}>{t}</option>
                  ))}
                </select>
              </div>

              <button type="submit" className="btn btn-primary w-full" disabled={loading}>
                <Sparkles size={16} /> Generate AI Recommendation
              </button>
            </form>
          </div>
        </div>

        {/* Response area */}
        <div className="card">
          <div className="card-header">
            <h2 className="card-title">AI Response</h2>
            {response && (
              <div className="flex gap-1 flex-wrap">
                <button className="btn btn-secondary btn-sm" onClick={handleSave} disabled={!!savedEntry}>
                  <Save size={14} /> Save
                </button>
                <button className="btn btn-primary btn-sm" onClick={handleCreateTasks}>
                  <ListPlus size={14} /> Create Tasks
                </button>
                <button className="btn btn-ghost btn-sm" onClick={handleClear}>
                  <Eraser size={14} /> Clear
                </button>
              </div>
            )}
          </div>
          <div className="card-body">
            {loading ? (
              <LoadingSpinner message="AI Mentor is analysing your project..." />
            ) : response ? (
              <div className="ai-response-card">
                <AISection icon={FileText} title="Requirement Understanding">
                  {response.requirementUnderstanding}
                </AISection>
                <AISection icon={Code} title="Frontend Tasks">
                  <ul>
                    {response.frontendTasks.map((t, i) => <li key={i}>{t}</li>)}
                  </ul>
                </AISection>
                <AISection icon={Code} title="Backend Tasks">
                  <ul>
                    {response.backendTasks.map((t, i) => <li key={i}>{t}</li>)}
                  </ul>
                </AISection>
                <AISection icon={Database} title="Database Tasks">
                  <ul>
                    {response.databaseTasks.map((t, i) => <li key={i}>{t}</li>)}
                  </ul>
                </AISection>
                <AISection icon={CheckSquare} title="Testing Steps">
                  <ul>
                    {response.testingSteps.map((t, i) => <li key={i}>{t}</li>)}
                  </ul>
                </AISection>
                <AISection icon={AlertTriangle} title="Possible Blockers">
                  <ul>
                    {response.possibleBlockers.map((t, i) => <li key={i}>{t}</li>)}
                  </ul>
                </AISection>
                <AISection icon={ArrowRightCircle} title="Recommended Next Action">
                  {response.recommendedNextAction}
                </AISection>
              </div>
            ) : (
              <EmptyState
                title="No response yet"
                message="Select a project, enter a requirement and generate an AI recommendation."
                icon={Sparkles}
              />
            )}
          </div>
        </div>
      </div>

      {savedEntry && (
        <div className="card mt-3">
          <div className="card-body">
            <p className="text-sm">
              Saved to AI History.{' '}
              <Link to="/ai-history">View all interactions</Link>
            </p>
          </div>
        </div>
      )}
    </div>
  )
}

function AISection({ icon: Icon, title, children }) {
  return (
    <div className="ai-section">
      <div className="ai-section-title">
        <Icon size={16} /> {title}
      </div>
      <div className="ai-section-body">{children}</div>
    </div>
  )
}
